version: "2"

services:
  eos:
    image: peterwillcn/eos 
    ports:
    - "8888:8888"
    - "9876:9876"
    volumes:
      - /data/store/eos:/opt/eos/bin/data-dir
      - ./config.ini:/config.ini
      - ../contracts:/usr/src/contracts
